### PR TITLE
Milestone 0.5.0

### PR DESCRIPTION
**Pull request by StandingPadAnimations**
PR for 0.5.0. Changes include the following:
- Update minimum version to Python 3.9
	- As this is a major release, we won't be running the MCprep build tests, as it's expected to break	
- Support for extensions
	- [x] `build_extension` toggle for legacy addons (extensions are the default now)
	- [x] Alternate implementation of Blender's Manifest verification with `lib_bpybuild_ext`
		- This is due to issues with including GPL code into a BSD licensed project
		- Known parity issues, but we're basing this off of the Blender documentation directly. I've pushed a few PRs upstream to help improve the documentation where possible, but one can only go so far 
	- [x] Support for building extensions and legacy addons	at the same time
		- [x] `is_extension` flag in `BabContext` 
	- [x] Restrict extension installation to Blender 4.2+
	- [x] Write tests for extension building
	- [ ] ~~`override_extension` setting to allow overriding the built-in `extension` action~~
- Improve experience with chains of actions
	- [x] Allow defining required actions if an action needs a previous action to run
		- [ ] `bab action-chain` command to visualize the chain of actions and the actions they depend on
		- [ ] ~~Create a system for actions to pass data to subsequent actions~~

### CODE REVIEW

**Comment by StandingPadAnimations** [comment]
Added test for extension building and building with legacy builds. Incredibly basic, but still a WIP

**Comment by StandingPadAnimations** [comment]
Considering this feature complete

**Review by TheDuckCow — APPROVED** [review]
Giving my approval, based on the fact that tests run fine and it still installs ok into MCprep:

```
...........
----------------------------------------------------------------------
Ran 11 tests in 0.105s

OK
```


Installed into my MCprep repo's venv via:
`pip install https://github.com/Moo-Ack-Productions/bpy-build/archive/milestone-5-0.zip`

And confirmed it built ok as a typical addon, and all MCprep tests there passed fine too.

And finally, it seems I'm successfully able to generate an extension of MCprep, although I need to manually remove the leading `_` of `_blender_manifest.toml`, and then when installing manually it recognizes it but trying to later manually enable the addon I get the below - not sure if that's a new thing or not.

```
Exception in module register(): /Users/patrickcrawford/Library/Application Support/Blender/4.3/extensions/user_default/mcprep/__init__.py
Traceback (most recent call last):
  File "/Applications/Blender 4.3/blender.app/Contents/Resources/4.3/scripts/modules/addon_utils.py", line 488, in enable
    mod.register()
  File "/Users/patrickcrawford/Library/Application Support/Blender/4.3/extensions/user_default/mcprep/__init__.py", line 65, in register
    load_modules.register(bl_info)
                          ^^^^^^^
NameError: name 'bl_info' is not defined
```

But, need not be blocking until we are forced to distribute MCprep as an extension Id's say. Let me know if you want more specific testing or review beyond that! Only lightly skimmed code, I'll admit I may not gather everything going on, but seems ok :) might be a decent idea to remind

**Comment by StandingPadAnimations** [comment]
> And finally, it seems I'm successfully able to generate an extension of MCprep, although I need to manually remove the leading `_` of `_blender_manifest.toml`, and then when installing manually it recognizes it but trying to later manually enable the addon I get the below - not sure if that's a new thing or not.
> 
> ```
> Exception in module register(): /Users/patrickcrawford/Library/Application Support/Blender/4.3/extensions/user_default/mcprep/__init__.py
> Traceback (most recent call last):
>   File "/Applications/Blender 4.3/blender.app/Contents/Resources/4.3/scripts/modules/addon_utils.py", line 488, in enable
>     mod.register()
>   File "/Users/patrickcrawford/Library/Application Support/Blender/4.3/extensions/user_default/mcprep/__init__.py", line 65, in register
>     load_modules.register(bl_info)
>                           ^^^^^^^
> NameError: name 'bl_info' is not defined
> ```

Blender is weird with extensions made from legacy addon codebases: if you define a `blender_manifest.toml` file, Blender deletes the whatever `bl_info` variable has been defined. However, since it's just an action called `extension` that can be overridden (we do have an override for MCprep, although that will need to be updated to take advantage of `lib_bpybuild_ext`), I think it should be safe to merge this.

**Pull request merged**
