### PR TITLE
Finalizing v0.3.0

### PR DESCRIPTION
**Pull request by StandingPadAnimations**
This is the finish of the BpyBuild rewrite. We just need to test this and make sure it works

### CODE REVIEW

**Comment by TheDuckCow** [comment]
Need to test this locally still, traveling today but will see if I have time tonight

**Comment by StandingPadAnimations** [comment]
I've pushed some changes to how BpyBuild handles configuration, specifically taking advantage of `cattrs` to read YAML configs into `attrs` objects (we already used `attrs` in BpyBuild prior to this since it's basically dataclasses with some pretty useful abilities, so using `cattrs` was pretty easy)

**Comment by StandingPadAnimations** [comment]
This should also make adding new config options easier as we no longer have to manually parse by hand (parsing JSON and YAML is a pain...)

**Review by TheDuckCow — CHANGES_REQUESTED** [review]
Sorry for the blanket request changes, and on today of all day! But, I feel it could require enough changes that we should chat on this point first.

One compatibility note, when trying to install the package directly: I'm getting this error, as I intentionally have a python venv with python 3.7, since that is the one supported by blender 2.80 (3.7.0 to be specific, and there are definite syntax things that only show up later that would break in python 3.7 that we want to avoid - I've run into them in other project).

We should be able to install the package with a python3.7 environment since we want developers to have that version of python be compatible. If this is a huge substantial difference that breaks *everything* you have been working on, then let's talk before doing any major rework - we will regardless have integration tests that run before releases on all versions of blender, so it's not like it would get in the way of that.

This happened after trying to run this command:
`pip install git+https://github.com/Moo-Ack-Productions/bpy-build@v0.3.0`

```
INFO: pip is looking at multiple versions of bpy-addon-build to determine which version is compatible with other requirements. This could take a while.
ERROR: Ignored the following yanked versions: 1.1.0, 1.6.0, 23.1.0
ERROR: Ignored the following versions that require a different python version: 23.2.0 Requires-Python >=3.8; 23.2.1 Requires-Python >=3.8; 23.2.2 Requires-Python >=3.8; 23.2.3 Requires-Python >=3.8
ERROR: Could not find a version that satisfies the requirement cattrs<24.0.0,>=23.2.3 (from bpy-addon-build) (from versions: 0.5.0, 0.6.0, 0.7.0, 0.8.0.dev0, 0.8.0, 0.8.1, 0.9.0, 0.9.2, 1.0.0rc0, 1.0.0, 1.1.1, 1.1.2, 1.2.0, 1.3.0, 1.4.0, 1.5.0, 1.7.0, 1.7.1, 1.8.0, 1.9.0, 1.10.0, 22.1.0, 22.2.0, 23.1.0rc0, 23.1.1, 23.1.2)
ERROR: No matching distribution found for cattrs<24.0.0,>=23.2.3
```

I notice python = "^3.9" in the pyproject.toml and `python-versions = ">=3.8"` in poetry.lock

Previous version of `bpy-addon-build` works fine in 3.7

**Comment by TheDuckCow** [comment]
As a side question, do these changes by chance allow for building the addon without having to re-copy all resource files? (ie the equivalent to the old -fast option)? That's still my biggest gripe, which slows down test-driven development, since 80% of the time running tests is actually the zipping install step.

**Comment by StandingPadAnimations** [comment]
Python 3.9 was chosen as the minimum version since most libraries have stopped supporting Python 3.7, so this was more out of neccesity. I'll recheck the minimum versions of the dependencies we use and see if I can reduce it (maybe Python 3.8?), but the only option for using Python 3.7 would be using older versions of libraries, which is not ideal (the old BpyBuild used to use outdated dependencies and suffered as a result, I don't want a repeat of that). 

As for the error, I'm not exactly sure what's going on, but I think it's related to to the Pip syntax. Pip syntax with packages on Git repos and a specific branch is not commonly used, so I probably made an error in the command syntax. 

As for the fast option, we don't have that in BpyBuild yet, but a workaround would be to keep the resources outside of the addon folder, and have a build action (like a production build action) that copies them only when specified (which would mean fast by default, slow on opt-in). In the future, BpyBuild will allow specifying what files to copy over for certain build actions

**Comment by TheDuckCow** [comment]
I've dealt with booleans in argparse in a 3.7 compatible way with some workarounds, so I'd argue for at least 3.8 to be closer if this is the _only_ problem.  This is what I've used before, and I think would work fine here:

```python
    parser.add_argument('-i', '--individual', action='store_true')
    parser.set_defaults(individual=False)
```

And based on what you said, I'm fine to go with 3.8+ for the build env. Like I said, actual syntax problems of 3.7 will show up in automated unit tests, would rather not increase the problems based on what we are avoiding here.

For reference, blender 2.90 uses 3.7.7, but blender 2.93 uses 3.9.2, so python 3.8 is still at least relevant within the 2.9x era.

Thanks for doing the investigation - it is indeed the holiday's, please enjoy family time and feel free to not reply back until later whenever you are more free!

**Comment by TheDuckCow** [comment]
(also whenever it _is_ ready for me to re-review, just click the refresh icon next to my user under the reviews section top-right!)

**Comment by StandingPadAnimations** [comment]
Alright, I got filters pushed (though I'll probably rename the config key to `ignore_filters` as its clearer compared to `filters`), you can try it on the MCprep repo with the dev action.

What makes these filters different from the Python based ones is that the Python based ones are only applied to the intermediate copy BpyBuild makes for actions (so the main folder isn't affected), whereas these are applied when making said copy.

**Review by TheDuckCow — APPROVED** [review]
Generally works fine, only problem is for some reason it's not finding blender version addon paths that end in 0, see my console output below:

```
Dev build, adding mcprep_dev.txt...
Installed to /Users/patrickcrawford/Library/Application Support/Blender/4.0/scripts/addons
Installed to /Users/patrickcrawford/Library/Application Support/Blender/3.6/scripts/addons
Installed to /Users/patrickcrawford/Library/Application Support/Blender/3.5/scripts/addons
Installed to /Users/patrickcrawford/Library/Application Support/Blender/3.4/scripts/addons
Installed to /Users/patrickcrawford/Library/Application Support/Blender/3.3/scripts/addons
Installed to /Users/patrickcrawford/Library/Application Support/Blender/3.2/scripts/addons
Installed to /Users/patrickcrawford/Library/Application Support/Blender/3.1/scripts/addons
Installed to /Users/patrickcrawford/Library/Application Support/Blender/3.0/scripts/addons
Installed to /Users/patrickcrawford/Library/Application Support/Blender/2.93/scripts/addons
Cound not find 2.9
Cound not find 2.83
Cound not find 2.8
(venv) mcprep copy $ open "/Users/patrickcrawford/Library/Application Support/Blender/2.90/scripts/addons"
(venv) mcprep copy $ ls "/Users/patrickcrawford/Library/Application Support/Blender/2.90/scripts/addons"
MCprep_addon			mcprep_addon_trackerid.json	poliigon-preview-generator	theory-tab
__MACOSX			poliigon-addon-blender		pro_lighting_studio		theory_id.json
blender-addon-updater		poliigon-material-converter	sarfis_pro
(venv) mcprep copy $ ls "/Users/patrickcrawford/Library/Application Support/Blender/2.83/scripts/addons"
ls: /Users/patrickcrawford/Library/Application Support/Blender/2.83/scripts/addons: No such file or directory
(venv) mcprep copy $ ls "/Users/patrickcrawford/Library/Application Support/Blender/2.80/scripts/addons"
MCprep_addon			mcprep_addon_trackerid.json	poliigon-addon-blender		poliigon-material-converter
(venv) mcprep copy $ 
```

I tried also modifying MCprep's bpy-build.yaml file to include both e.g. 2.80 and 2.8, neither got picked up. Looking briefly at the code, it seems like it would work with the try/retry you do, but apparently not. Not a deal breaker for me but would be nice to patch soon, could be a follow up pr for v0.3.0 if we just want to get this out.

**Comment by StandingPadAnimations** [comment]
Should be fixed now

**Comment by StandingPadAnimations** [comment]
Will push to PyPI now

**Pull request merged**
